name: Push to GitHub
'on':
  push:
    branches:
    - main
jobs:
  push-changes:
    name: Push changes to GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Configure Git
      run: ls
